# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - kml-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://kmlbackend.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_390e2c3f13ef4127b429e32c5bc338fa }}
        password: ${{ secrets.AzureAppService_ContainerPassword_dd76e672c7904e3da5df084884a97de4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: kmlbackend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_390e2c3f13ef4127b429e32c5bc338fa }}/kmlbackend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kml-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_344277df6b284a52be38038a19e6ccd7 }}
        images: 'kmlbackend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_390e2c3f13ef4127b429e32c5bc338fa }}/kmlbackend:${{ github.sha }}'